name: Docker Image CI

on:
  push:
    branches:
    - main
    - staging
    - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PWD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/lamp-example:$GITHUB_SHA
    - name: Docker push image to hub
      run: docker push ${{secrets.DOCKER_USER}}/lamp-example:$GITHUB_SHA
